# Generated by Django 2.2.6 on 2019-12-11 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0007_auto_20191211_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 4, 46, 8, 709111, tzinfo=utc), verbose_name='date published'),
        ),
    ]
